version: "3.2"

services:
  dev:
    container_name: bittok
    image: paritytech/ci-linux:production
    working_dir: /var/www/bittok
    ports:
      - "9944:9944"
    environment:
      - CARGO_HOME=/var/www/bittok/.cargo
    volumes:
      - .:/var/www/bittok
      - type: bind
        source: ./.local
        target: /root/.local
    command: bash -c "cargo build --release && ./target/release/bittok --dev --ws-external"
