[package]
name = "type-utils"
authors = ['Bittok Network <https://github.com/bittok-network>']
edition = '2018'
license = 'GPL-3.0'
homepage = 'https://bittok.finance'
repository = 'https://github.com/bittok-network/bittok'
version = '0.9.0'

[dependencies]
